#server:
#  port: 8081
#  servlet:
#    context-path: /wlf
#
#date: "4月4号"
#
#todo:
#  thing: 今天是${date},我们去看电影
#
#
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/product?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: 123456
#
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update